### ISSUE TITLE
where in ctx.state do others store their application user model object

### ISSUE THREAD

**Issue by mpvosseller** [uhop/koa-cognito-middleware#1]
My application has a `User` model object (database object) and I want to store a reference to it in the Koa context. `ctx.state.user` seems like the ideal place to put it but `koa-cognito-middleware` uses that path for the Cognito user object.

For now I'm storing the application `User` object at `ctx.state.userModel` but that doesn't feel great. The "high level" object gets a worse path name than the "lower level" object.

Curious what others do? 

Would it be better to have `koa-cognito-middleware` use a path like `ctx.state.cognito` so as to reserve the `ctx.state.user` for the application?

**Comment by uhop** [comment]
See if a new version [1.4.4](https://github.com/uhop/koa-cognito-middleware/tree/1.4.4) works for you.

The relevant piece of documentation (in README):

-----

## `getUser.stateUserProperty`

*(Since 1.4.4):* This is a property name to hold a user object. It can be a string or a `Symbol`. Default: `'user'`.

Usually it is assigned right after obtaining `getUser()`:

```js
const getUser = require('koa-cognito-middleware');
getUser.stateUserProperty = 'cognitoUser';
const {isAuthenticated, hasScope, hasGroup, isAllowed} = getUser;
```

**Comment by mpvosseller** [comment]
It works! Thanks so much.  👍
